<?php

use App\SignupData;
use Illuminate\Database\Seeder;

class SignupTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        SignupData::create([
            'Gender_data'=>'Male',
            'DOB_day_data'=>'1',
            'DOB_month_data'=>'January',
            'DOB_year_data'=>'2000',
            'RegistrationReason_data'=>'I am registering to find myself partner',
            'HearAboutUs_data'=>'Google',
        ]);

        SignupData::create([
            'Gender_data'=>'Female',
            'DOB_day_data'=>'2',
            'DOB_month_data'=>'February',
            'DOB_year_data'=>'1999',
            'RegistrationReason_data'=>'I am registering to find my sister a partner',
            'HearAboutUs_data'=>'Friend or Family',
        ]);
        SignupData::create([
            'DOB_day_data'=>'3',
            'DOB_month_data'=>'March',
            'DOB_year_data'=>'1998',
            'RegistrationReason_data'=>'I am registering to find my brother a partner',
            'HearAboutUs_data'=>'Radio',
        ]);
        SignupData::create([
            'DOB_day_data'=>'4',
            'DOB_month_data'=>'April',
            'DOB_year_data'=>'1997',
            'RegistrationReason_data'=>'I am registering to find my son a partner',
            'HearAboutUs_data'=>'Newspaper',
        ]);

         SignupData::create([
            'DOB_day_data'=>'5',
            'DOB_month_data'=>'May',
            'DOB_year_data'=>'1996',
            'RegistrationReason_data'=>'I am registering to find my daughter a partner',
            'HearAboutUs_data'=>'Tv Advert',
        ]);
        SignupData::create([
            'DOB_day_data'=>'6',
            'DOB_month_data'=>'June',
            'DOB_year_data'=>'1995',
            'RegistrationReason_data'=>'I am registering to find my friend a partner',

        ]);
         SignupData::create([
            'DOB_day_data'=>'7',
            'DOB_month_data'=>'July',
            'DOB_year_data'=>'1994',
            'RegistrationReason_data'=>'Others',

        ]);
        SignupData::create([
            'DOB_day_data'=>'8',
            'DOB_month_data'=>'August',
            'DOB_year_data'=>'1993',
        ]);
        SignupData::create([
            'DOB_day_data'=>'9',
            'DOB_month_data'=>'September',
            'DOB_year_data'=>'1992',
        ]);
        SignupData::create([
            'DOB_day_data'=>'10',
            'DOB_month_data'=>'October',
            'DOB_year_data'=>'1991',
        ]);
        SignupData::create([
            'DOB_day_data'=>'11',
            'DOB_month_data'=>'November',
            'DOB_year_data'=>'1990',
        ]);
        SignupData::create([
            'DOB_day_data'=>'12',
            'DOB_month_data'=>'December',
            'DOB_year_data'=>'1989',
        ]);
        SignupData::create([
            'DOB_day_data'=>'13',
            'DOB_year_data'=>'1988',
        ]);
        SignupData::create([
            'DOB_day_data'=>'14',
            'DOB_year_data'=>'1987',
        ]);
        SignupData::create([
            'DOB_day_data'=>'15',
            'DOB_year_data'=>'1986',
        ]);
        SignupData::create([
            'DOB_day_data'=>'16',
            'DOB_year_data'=>'1985',
        ]);
        SignupData::create([
            'DOB_day_data'=>'17',
            'DOB_year_data'=>'1984',
        ]);
        SignupData::create([
            'DOB_day_data'=>'18',
            'DOB_year_data'=>'1983',
        ]);
        SignupData::create([
            'DOB_day_data'=>'19',
            'DOB_year_data'=>'1982',
        ]);
        SignupData::create([
            'DOB_day_data'=>'20',
            'DOB_year_data'=>'1981',
        ]);
        SignupData::create([
            'DOB_day_data'=>'21',
            'DOB_year_data'=>'1980',
        ]);
        SignupData::create([
            'DOB_day_data'=>'22',
            'DOB_year_data'=>'1979',
        ]);
        SignupData::create([
            'DOB_day_data'=>'23',
            'DOB_year_data'=>'1978',
        ]);
        SignupData::create([
            'DOB_day_data'=>'24',
            'DOB_year_data'=>'1977',
        ]);
        SignupData::create([
            'DOB_day_data'=>'25',
            'DOB_year_data'=>'1976',
        ]);
        SignupData::create([
            'DOB_day_data'=>'26',
            'DOB_year_data'=>'1975',
        ]);
        SignupData::create([
            'DOB_day_data'=>'27',
            'DOB_year_data'=>'1974',
        ]);
        SignupData::create([
            'DOB_day_data'=>'28',
            'DOB_year_data'=>'1973',
        ]);
        SignupData::create([
            'DOB_day_data'=>'29',
            'DOB_year_data'=>'1972',
        ]);
        SignupData::create([
            'DOB_day_data'=>'30',
            'DOB_year_data'=>'1971',
        ]);
        SignupData::create([
            'DOB_day_data'=>'31',
            'DOB_year_data'=>'1970',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1969',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1968',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1967',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1966',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1965',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1964',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1963',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1962',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1961',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1960',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1959',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1958',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1957',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1956',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1955',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1954',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1953',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1952',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1951',
        ]);
        SignupData::create([
            'DOB_year_data'=>'1950',
        ]);
        
    }
}

